"""Add assigned_to

Revision ID: adc54767cf5b
Revises: f278f3e38f84
Create Date: 2026-06-29 17:27:43.852844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc54767cf5b'
down_revision: Union[str, Sequence[str], None] = 'f278f3e38f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###
