"""Add comments table

Revision ID: df027bc53cc7
Revises: adc54767cf5b
Create Date: 2026-06-29 18:20:08.907586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df027bc53cc7'
down_revision: Union[str, Sequence[str], None] = 'adc54767cf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
